/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.koko.node;

import org.koko.analysis.*;

@SuppressWarnings("nls")
public final class APureExpr extends PExpr
{
    private PPureExpr _pureExpr_;

    public APureExpr()
    {
        // Constructor
    }

    public APureExpr(
        @SuppressWarnings("hiding") PPureExpr _pureExpr_)
    {
        // Constructor
        setPureExpr(_pureExpr_);

    }

    @Override
    public Object clone()
    {
        return new APureExpr(
            cloneNode(this._pureExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPureExpr(this);
    }

    public PPureExpr getPureExpr()
    {
        return this._pureExpr_;
    }

    public void setPureExpr(PPureExpr node)
    {
        if(this._pureExpr_ != null)
        {
            this._pureExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pureExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pureExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pureExpr_ == child)
        {
            this._pureExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pureExpr_ == oldChild)
        {
            setPureExpr((PPureExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
