/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.analysis;

import org.newkoko.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAGrammar(AGrammar node);
    void caseAAssignNewIntStatement(AAssignNewIntStatement node);
    void caseAAssignNewDoubleStatement(AAssignNewDoubleStatement node);
    void caseAAssignStatement(AAssignStatement node);
    void caseAPlusExp(APlusExp node);
    void caseAMinusExp(AMinusExp node);
    void caseADivExp(ADivExp node);
    void caseAMulExp(AMulExp node);
    void caseANumberExp(ANumberExp node);

    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMul(TMul node);
    void caseTDiv(TDiv node);
    void caseTSemi(TSemi node);
    void caseTInt(TInt node);
    void caseTDouble(TDouble node);
    void caseTIdentifier(TIdentifier node);
    void caseTEquals(TEquals node);
    void caseTBlank(TBlank node);
    void caseTNumber(TNumber node);
    void caseEOF(EOF node);
}
