/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.koko.node;

import org.koko.analysis.*;

@SuppressWarnings("nls")
public final class ABindExpr extends PExpr
{
    private PBindExpr _bindExpr_;

    public ABindExpr()
    {
        // Constructor
    }

    public ABindExpr(
        @SuppressWarnings("hiding") PBindExpr _bindExpr_)
    {
        // Constructor
        setBindExpr(_bindExpr_);

    }

    @Override
    public Object clone()
    {
        return new ABindExpr(
            cloneNode(this._bindExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABindExpr(this);
    }

    public PBindExpr getBindExpr()
    {
        return this._bindExpr_;
    }

    public void setBindExpr(PBindExpr node)
    {
        if(this._bindExpr_ != null)
        {
            this._bindExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bindExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bindExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bindExpr_ == child)
        {
            this._bindExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bindExpr_ == oldChild)
        {
            setBindExpr((PBindExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
