/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.koko.node;

import java.util.*;
import org.koko.analysis.*;

@SuppressWarnings("nls")
public final class ACmpPureExpr extends PPureExpr
{
    private TCmp _op_;
    private final LinkedList<PPureExpr> _args_ = new LinkedList<PPureExpr>();

    public ACmpPureExpr()
    {
        // Constructor
    }

    public ACmpPureExpr(
        @SuppressWarnings("hiding") TCmp _op_,
        @SuppressWarnings("hiding") List<?> _args_)
    {
        // Constructor
        setOp(_op_);

        setArgs(_args_);

    }

    @Override
    public Object clone()
    {
        return new ACmpPureExpr(
            cloneNode(this._op_),
            cloneList(this._args_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACmpPureExpr(this);
    }

    public TCmp getOp()
    {
        return this._op_;
    }

    public void setOp(TCmp node)
    {
        if(this._op_ != null)
        {
            this._op_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op_ = node;
    }

    public LinkedList<PPureExpr> getArgs()
    {
        return this._args_;
    }

    public void setArgs(List<?> list)
    {
        for(PPureExpr e : this._args_)
        {
            e.parent(null);
        }
        this._args_.clear();

        for(Object obj_e : list)
        {
            PPureExpr e = (PPureExpr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._args_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._op_)
            + toString(this._args_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._op_ == child)
        {
            this._op_ = null;
            return;
        }

        if(this._args_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._op_ == oldChild)
        {
            setOp((TCmp) newChild);
            return;
        }

        for(ListIterator<PPureExpr> i = this._args_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPureExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
