/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import java.util.*;
import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AArgList extends PArgList
{
    private PValue _value_;
    private final LinkedList<PArgListTail> _argListTail_ = new LinkedList<PArgListTail>();

    public AArgList()
    {
        // Constructor
    }

    public AArgList(
        @SuppressWarnings("hiding") PValue _value_,
        @SuppressWarnings("hiding") List<?> _argListTail_)
    {
        // Constructor
        setValue(_value_);

        setArgListTail(_argListTail_);

    }

    @Override
    public Object clone()
    {
        return new AArgList(
            cloneNode(this._value_),
            cloneList(this._argListTail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgList(this);
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    public LinkedList<PArgListTail> getArgListTail()
    {
        return this._argListTail_;
    }

    public void setArgListTail(List<?> list)
    {
        for(PArgListTail e : this._argListTail_)
        {
            e.parent(null);
        }
        this._argListTail_.clear();

        for(Object obj_e : list)
        {
            PArgListTail e = (PArgListTail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._argListTail_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._value_)
            + toString(this._argListTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        if(this._argListTail_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator<PArgListTail> i = this._argListTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArgListTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
