/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AAssignVariableSimpleStatement extends PSimpleStatement
{
    private PAssignVariable _assignVariable_;

    public AAssignVariableSimpleStatement()
    {
        // Constructor
    }

    public AAssignVariableSimpleStatement(
        @SuppressWarnings("hiding") PAssignVariable _assignVariable_)
    {
        // Constructor
        setAssignVariable(_assignVariable_);

    }

    @Override
    public Object clone()
    {
        return new AAssignVariableSimpleStatement(
            cloneNode(this._assignVariable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignVariableSimpleStatement(this);
    }

    public PAssignVariable getAssignVariable()
    {
        return this._assignVariable_;
    }

    public void setAssignVariable(PAssignVariable node)
    {
        if(this._assignVariable_ != null)
        {
            this._assignVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignVariable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignVariable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignVariable_ == child)
        {
            this._assignVariable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignVariable_ == oldChild)
        {
            setAssignVariable((PAssignVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
