/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class ADivEqAssignOp extends PAssignOp
{
    private TDivEqual _divEqual_;

    public ADivEqAssignOp()
    {
        // Constructor
    }

    public ADivEqAssignOp(
        @SuppressWarnings("hiding") TDivEqual _divEqual_)
    {
        // Constructor
        setDivEqual(_divEqual_);

    }

    @Override
    public Object clone()
    {
        return new ADivEqAssignOp(
            cloneNode(this._divEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivEqAssignOp(this);
    }

    public TDivEqual getDivEqual()
    {
        return this._divEqual_;
    }

    public void setDivEqual(TDivEqual node)
    {
        if(this._divEqual_ != null)
        {
            this._divEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._divEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._divEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._divEqual_ == child)
        {
            this._divEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._divEqual_ == oldChild)
        {
            setDivEqual((TDivEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
