/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AEqEqRelationOp extends PRelationOp
{
    private TEqEq _eqEq_;

    public AEqEqRelationOp()
    {
        // Constructor
    }

    public AEqEqRelationOp(
        @SuppressWarnings("hiding") TEqEq _eqEq_)
    {
        // Constructor
        setEqEq(_eqEq_);

    }

    @Override
    public Object clone()
    {
        return new AEqEqRelationOp(
            cloneNode(this._eqEq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqEqRelationOp(this);
    }

    public TEqEq getEqEq()
    {
        return this._eqEq_;
    }

    public void setEqEq(TEqEq node)
    {
        if(this._eqEq_ != null)
        {
            this._eqEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eqEq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eqEq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eqEq_ == child)
        {
            this._eqEq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eqEq_ == oldChild)
        {
            setEqEq((TEqEq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
