/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AFunction extends PFunction
{
    private PFunctionDeclaration _functionDeclaration_;
    private PFunctionBody _functionBody_;

    public AFunction()
    {
        // Constructor
    }

    public AFunction(
        @SuppressWarnings("hiding") PFunctionDeclaration _functionDeclaration_,
        @SuppressWarnings("hiding") PFunctionBody _functionBody_)
    {
        // Constructor
        setFunctionDeclaration(_functionDeclaration_);

        setFunctionBody(_functionBody_);

    }

    @Override
    public Object clone()
    {
        return new AFunction(
            cloneNode(this._functionDeclaration_),
            cloneNode(this._functionBody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunction(this);
    }

    public PFunctionDeclaration getFunctionDeclaration()
    {
        return this._functionDeclaration_;
    }

    public void setFunctionDeclaration(PFunctionDeclaration node)
    {
        if(this._functionDeclaration_ != null)
        {
            this._functionDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionDeclaration_ = node;
    }

    public PFunctionBody getFunctionBody()
    {
        return this._functionBody_;
    }

    public void setFunctionBody(PFunctionBody node)
    {
        if(this._functionBody_ != null)
        {
            this._functionBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionBody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionDeclaration_)
            + toString(this._functionBody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionDeclaration_ == child)
        {
            this._functionDeclaration_ = null;
            return;
        }

        if(this._functionBody_ == child)
        {
            this._functionBody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._functionDeclaration_ == oldChild)
        {
            setFunctionDeclaration((PFunctionDeclaration) newChild);
            return;
        }

        if(this._functionBody_ == oldChild)
        {
            setFunctionBody((PFunctionBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
