/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AGtEqRelationOp extends PRelationOp
{
    private TGtEq _gtEq_;

    public AGtEqRelationOp()
    {
        // Constructor
    }

    public AGtEqRelationOp(
        @SuppressWarnings("hiding") TGtEq _gtEq_)
    {
        // Constructor
        setGtEq(_gtEq_);

    }

    @Override
    public Object clone()
    {
        return new AGtEqRelationOp(
            cloneNode(this._gtEq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtEqRelationOp(this);
    }

    public TGtEq getGtEq()
    {
        return this._gtEq_;
    }

    public void setGtEq(TGtEq node)
    {
        if(this._gtEq_ != null)
        {
            this._gtEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gtEq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._gtEq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._gtEq_ == child)
        {
            this._gtEq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._gtEq_ == oldChild)
        {
            setGtEq((TGtEq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
