/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AMinusEqAssignOp extends PAssignOp
{
    private TMinusEqual _minusEqual_;

    public AMinusEqAssignOp()
    {
        // Constructor
    }

    public AMinusEqAssignOp(
        @SuppressWarnings("hiding") TMinusEqual _minusEqual_)
    {
        // Constructor
        setMinusEqual(_minusEqual_);

    }

    @Override
    public Object clone()
    {
        return new AMinusEqAssignOp(
            cloneNode(this._minusEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusEqAssignOp(this);
    }

    public TMinusEqual getMinusEqual()
    {
        return this._minusEqual_;
    }

    public void setMinusEqual(TMinusEqual node)
    {
        if(this._minusEqual_ != null)
        {
            this._minusEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusEqual_ == child)
        {
            this._minusEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusEqual_ == oldChild)
        {
            setMinusEqual((TMinusEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
