/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class ARelationOpBinaryOp extends PBinaryOp
{
    private PRelationOp _relationOp_;

    public ARelationOpBinaryOp()
    {
        // Constructor
    }

    public ARelationOpBinaryOp(
        @SuppressWarnings("hiding") PRelationOp _relationOp_)
    {
        // Constructor
        setRelationOp(_relationOp_);

    }

    @Override
    public Object clone()
    {
        return new ARelationOpBinaryOp(
            cloneNode(this._relationOp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelationOpBinaryOp(this);
    }

    public PRelationOp getRelationOp()
    {
        return this._relationOp_;
    }

    public void setRelationOp(PRelationOp node)
    {
        if(this._relationOp_ != null)
        {
            this._relationOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationOp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relationOp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relationOp_ == child)
        {
            this._relationOp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relationOp_ == oldChild)
        {
            setRelationOp((PRelationOp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
