/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleStatementStatement extends PStatement
{
    private PSimpleStatement _simpleStatement_;
    private TSemicolon _semicolon_;

    public ASimpleStatementStatement()
    {
        // Constructor
    }

    public ASimpleStatementStatement(
        @SuppressWarnings("hiding") PSimpleStatement _simpleStatement_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setSimpleStatement(_simpleStatement_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleStatementStatement(
            cloneNode(this._simpleStatement_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleStatementStatement(this);
    }

    public PSimpleStatement getSimpleStatement()
    {
        return this._simpleStatement_;
    }

    public void setSimpleStatement(PSimpleStatement node)
    {
        if(this._simpleStatement_ != null)
        {
            this._simpleStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleStatement_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleStatement_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleStatement_ == child)
        {
            this._simpleStatement_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleStatement_ == oldChild)
        {
            setSimpleStatement((PSimpleStatement) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
