/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AStarEqAssignOp extends PAssignOp
{
    private TStarEqual _starEqual_;

    public AStarEqAssignOp()
    {
        // Constructor
    }

    public AStarEqAssignOp(
        @SuppressWarnings("hiding") TStarEqual _starEqual_)
    {
        // Constructor
        setStarEqual(_starEqual_);

    }

    @Override
    public Object clone()
    {
        return new AStarEqAssignOp(
            cloneNode(this._starEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStarEqAssignOp(this);
    }

    public TStarEqual getStarEqual()
    {
        return this._starEqual_;
    }

    public void setStarEqual(TStarEqual node)
    {
        if(this._starEqual_ != null)
        {
            this._starEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._starEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._starEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._starEqual_ == child)
        {
            this._starEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._starEqual_ == oldChild)
        {
            setStarEqual((TStarEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
