/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AAmpersandAmpersandBinaryOp extends PBinaryOp
{
    private TAmpersandAmpersand _ampersandAmpersand_;

    public AAmpersandAmpersandBinaryOp()
    {
        // Constructor
    }

    public AAmpersandAmpersandBinaryOp(
        @SuppressWarnings("hiding") TAmpersandAmpersand _ampersandAmpersand_)
    {
        // Constructor
        setAmpersandAmpersand(_ampersandAmpersand_);

    }

    @Override
    public Object clone()
    {
        return new AAmpersandAmpersandBinaryOp(
            cloneNode(this._ampersandAmpersand_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAmpersandAmpersandBinaryOp(this);
    }

    public TAmpersandAmpersand getAmpersandAmpersand()
    {
        return this._ampersandAmpersand_;
    }

    public void setAmpersandAmpersand(TAmpersandAmpersand node)
    {
        if(this._ampersandAmpersand_ != null)
        {
            this._ampersandAmpersand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ampersandAmpersand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ampersandAmpersand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ampersandAmpersand_ == child)
        {
            this._ampersandAmpersand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ampersandAmpersand_ == oldChild)
        {
            setAmpersandAmpersand((TAmpersandAmpersand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
