/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AAssignVariable extends PAssignVariable
{
    private TIdentifier _identifier_;
    private PAssignOp _assignOp_;
    private PRightHandSide _rightHandSide_;

    public AAssignVariable()
    {
        // Constructor
    }

    public AAssignVariable(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PAssignOp _assignOp_,
        @SuppressWarnings("hiding") PRightHandSide _rightHandSide_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setAssignOp(_assignOp_);

        setRightHandSide(_rightHandSide_);

    }

    @Override
    public Object clone()
    {
        return new AAssignVariable(
            cloneNode(this._identifier_),
            cloneNode(this._assignOp_),
            cloneNode(this._rightHandSide_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignVariable(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PAssignOp getAssignOp()
    {
        return this._assignOp_;
    }

    public void setAssignOp(PAssignOp node)
    {
        if(this._assignOp_ != null)
        {
            this._assignOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignOp_ = node;
    }

    public PRightHandSide getRightHandSide()
    {
        return this._rightHandSide_;
    }

    public void setRightHandSide(PRightHandSide node)
    {
        if(this._rightHandSide_ != null)
        {
            this._rightHandSide_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightHandSide_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._assignOp_)
            + toString(this._rightHandSide_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._assignOp_ == child)
        {
            this._assignOp_ = null;
            return;
        }

        if(this._rightHandSide_ == child)
        {
            this._rightHandSide_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._assignOp_ == oldChild)
        {
            setAssignOp((PAssignOp) newChild);
            return;
        }

        if(this._rightHandSide_ == oldChild)
        {
            setRightHandSide((PRightHandSide) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
