/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class ADoubleConstant extends PConstant
{
    private TMinus _minus_;
    private TFloatingConstant _floatingConstant_;

    public ADoubleConstant()
    {
        // Constructor
    }

    public ADoubleConstant(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") TFloatingConstant _floatingConstant_)
    {
        // Constructor
        setMinus(_minus_);

        setFloatingConstant(_floatingConstant_);

    }

    @Override
    public Object clone()
    {
        return new ADoubleConstant(
            cloneNode(this._minus_),
            cloneNode(this._floatingConstant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADoubleConstant(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public TFloatingConstant getFloatingConstant()
    {
        return this._floatingConstant_;
    }

    public void setFloatingConstant(TFloatingConstant node)
    {
        if(this._floatingConstant_ != null)
        {
            this._floatingConstant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._floatingConstant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._floatingConstant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._floatingConstant_ == child)
        {
            this._floatingConstant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._floatingConstant_ == oldChild)
        {
            setFloatingConstant((TFloatingConstant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
