/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AExclMarkUnaryOp extends PUnaryOp
{
    private TExclMark _exclMark_;

    public AExclMarkUnaryOp()
    {
        // Constructor
    }

    public AExclMarkUnaryOp(
        @SuppressWarnings("hiding") TExclMark _exclMark_)
    {
        // Constructor
        setExclMark(_exclMark_);

    }

    @Override
    public Object clone()
    {
        return new AExclMarkUnaryOp(
            cloneNode(this._exclMark_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExclMarkUnaryOp(this);
    }

    public TExclMark getExclMark()
    {
        return this._exclMark_;
    }

    public void setExclMark(TExclMark node)
    {
        if(this._exclMark_ != null)
        {
            this._exclMark_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exclMark_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exclMark_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exclMark_ == child)
        {
            this._exclMark_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exclMark_ == oldChild)
        {
            setExclMark((TExclMark) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
