/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class ALtEqRelationOp extends PRelationOp
{
    private TLtEq _ltEq_;

    public ALtEqRelationOp()
    {
        // Constructor
    }

    public ALtEqRelationOp(
        @SuppressWarnings("hiding") TLtEq _ltEq_)
    {
        // Constructor
        setLtEq(_ltEq_);

    }

    @Override
    public Object clone()
    {
        return new ALtEqRelationOp(
            cloneNode(this._ltEq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALtEqRelationOp(this);
    }

    public TLtEq getLtEq()
    {
        return this._ltEq_;
    }

    public void setLtEq(TLtEq node)
    {
        if(this._ltEq_ != null)
        {
            this._ltEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ltEq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ltEq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ltEq_ == child)
        {
            this._ltEq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ltEq_ == oldChild)
        {
            setLtEq((TLtEq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
