/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AModEqAssignOp extends PAssignOp
{
    private TModEqual _modEqual_;

    public AModEqAssignOp()
    {
        // Constructor
    }

    public AModEqAssignOp(
        @SuppressWarnings("hiding") TModEqual _modEqual_)
    {
        // Constructor
        setModEqual(_modEqual_);

    }

    @Override
    public Object clone()
    {
        return new AModEqAssignOp(
            cloneNode(this._modEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModEqAssignOp(this);
    }

    public TModEqual getModEqual()
    {
        return this._modEqual_;
    }

    public void setModEqual(TModEqual node)
    {
        if(this._modEqual_ != null)
        {
            this._modEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._modEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._modEqual_ == child)
        {
            this._modEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._modEqual_ == oldChild)
        {
            setModEqual((TModEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
