/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class ANewVariableSimpleStatement extends PSimpleStatement
{
    private PNewVariable _newVariable_;

    public ANewVariableSimpleStatement()
    {
        // Constructor
    }

    public ANewVariableSimpleStatement(
        @SuppressWarnings("hiding") PNewVariable _newVariable_)
    {
        // Constructor
        setNewVariable(_newVariable_);

    }

    @Override
    public Object clone()
    {
        return new ANewVariableSimpleStatement(
            cloneNode(this._newVariable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewVariableSimpleStatement(this);
    }

    public PNewVariable getNewVariable()
    {
        return this._newVariable_;
    }

    public void setNewVariable(PNewVariable node)
    {
        if(this._newVariable_ != null)
        {
            this._newVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newVariable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._newVariable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._newVariable_ == child)
        {
            this._newVariable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._newVariable_ == oldChild)
        {
            setNewVariable((PNewVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
