/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class ANewVariable extends PNewVariable
{
    private PType _type_;
    private TIdentifier _identifier_;
    private TEq _eq_;
    private PRightHandSide _rightHandSide_;

    public ANewVariable()
    {
        // Constructor
    }

    public ANewVariable(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") TEq _eq_,
        @SuppressWarnings("hiding") PRightHandSide _rightHandSide_)
    {
        // Constructor
        setType(_type_);

        setIdentifier(_identifier_);

        setEq(_eq_);

        setRightHandSide(_rightHandSide_);

    }

    @Override
    public Object clone()
    {
        return new ANewVariable(
            cloneNode(this._type_),
            cloneNode(this._identifier_),
            cloneNode(this._eq_),
            cloneNode(this._rightHandSide_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewVariable(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public TEq getEq()
    {
        return this._eq_;
    }

    public void setEq(TEq node)
    {
        if(this._eq_ != null)
        {
            this._eq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eq_ = node;
    }

    public PRightHandSide getRightHandSide()
    {
        return this._rightHandSide_;
    }

    public void setRightHandSide(PRightHandSide node)
    {
        if(this._rightHandSide_ != null)
        {
            this._rightHandSide_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightHandSide_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._identifier_)
            + toString(this._eq_)
            + toString(this._rightHandSide_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._eq_ == child)
        {
            this._eq_ = null;
            return;
        }

        if(this._rightHandSide_ == child)
        {
            this._rightHandSide_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._eq_ == oldChild)
        {
            setEq((TEq) newChild);
            return;
        }

        if(this._rightHandSide_ == oldChild)
        {
            setRightHandSide((PRightHandSide) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
