/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import java.util.*;
import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AParameterList extends PParameterList
{
    private PParameter _parameter_;
    private final LinkedList<PNextParameter> _nextParameter_ = new LinkedList<PNextParameter>();

    public AParameterList()
    {
        // Constructor
    }

    public AParameterList(
        @SuppressWarnings("hiding") PParameter _parameter_,
        @SuppressWarnings("hiding") List<?> _nextParameter_)
    {
        // Constructor
        setParameter(_parameter_);

        setNextParameter(_nextParameter_);

    }

    @Override
    public Object clone()
    {
        return new AParameterList(
            cloneNode(this._parameter_),
            cloneList(this._nextParameter_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameterList(this);
    }

    public PParameter getParameter()
    {
        return this._parameter_;
    }

    public void setParameter(PParameter node)
    {
        if(this._parameter_ != null)
        {
            this._parameter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parameter_ = node;
    }

    public LinkedList<PNextParameter> getNextParameter()
    {
        return this._nextParameter_;
    }

    public void setNextParameter(List<?> list)
    {
        for(PNextParameter e : this._nextParameter_)
        {
            e.parent(null);
        }
        this._nextParameter_.clear();

        for(Object obj_e : list)
        {
            PNextParameter e = (PNextParameter) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._nextParameter_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parameter_)
            + toString(this._nextParameter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parameter_ == child)
        {
            this._parameter_ = null;
            return;
        }

        if(this._nextParameter_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parameter_ == oldChild)
        {
            setParameter((PParameter) newChild);
            return;
        }

        for(ListIterator<PNextParameter> i = this._nextParameter_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PNextParameter) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
