/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class APlusEqAssignOp extends PAssignOp
{
    private TPlusEqual _plusEqual_;

    public APlusEqAssignOp()
    {
        // Constructor
    }

    public APlusEqAssignOp(
        @SuppressWarnings("hiding") TPlusEqual _plusEqual_)
    {
        // Constructor
        setPlusEqual(_plusEqual_);

    }

    @Override
    public Object clone()
    {
        return new APlusEqAssignOp(
            cloneNode(this._plusEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusEqAssignOp(this);
    }

    public TPlusEqual getPlusEqual()
    {
        return this._plusEqual_;
    }

    public void setPlusEqual(TPlusEqual node)
    {
        if(this._plusEqual_ != null)
        {
            this._plusEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusEqual_ == child)
        {
            this._plusEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusEqual_ == oldChild)
        {
            setPlusEqual((TPlusEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
