/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import java.util.*;
import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private final LinkedList<PFunctionOrStatement> _functionOrStatement_ = new LinkedList<PFunctionOrStatement>();

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") List<?> _functionOrStatement_)
    {
        // Constructor
        setFunctionOrStatement(_functionOrStatement_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneList(this._functionOrStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList<PFunctionOrStatement> getFunctionOrStatement()
    {
        return this._functionOrStatement_;
    }

    public void setFunctionOrStatement(List<?> list)
    {
        for(PFunctionOrStatement e : this._functionOrStatement_)
        {
            e.parent(null);
        }
        this._functionOrStatement_.clear();

        for(Object obj_e : list)
        {
            PFunctionOrStatement e = (PFunctionOrStatement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._functionOrStatement_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionOrStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionOrStatement_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PFunctionOrStatement> i = this._functionOrStatement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFunctionOrStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
