/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class AUnaryOpUnaryExpression extends PUnaryExpression
{
    private PUnaryOp _unaryOp_;
    private TIdentifier _identifier_;

    public AUnaryOpUnaryExpression()
    {
        // Constructor
    }

    public AUnaryOpUnaryExpression(
        @SuppressWarnings("hiding") PUnaryOp _unaryOp_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setUnaryOp(_unaryOp_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryOpUnaryExpression(
            cloneNode(this._unaryOp_),
            cloneNode(this._identifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryOpUnaryExpression(this);
    }

    public PUnaryOp getUnaryOp()
    {
        return this._unaryOp_;
    }

    public void setUnaryOp(PUnaryOp node)
    {
        if(this._unaryOp_ != null)
        {
            this._unaryOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryOp_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unaryOp_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unaryOp_ == child)
        {
            this._unaryOp_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unaryOp_ == oldChild)
        {
            setUnaryOp((PUnaryOp) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
