/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.newkoko.c.node;

import org.newkoko.c.analysis.*;

@SuppressWarnings("nls")
public final class TDivEqual extends Token
{
    public TDivEqual()
    {
        super.setText("/=");
    }

    public TDivEqual(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDivEqual(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDivEqual(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDivEqual text.");
    }
}
