/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.koko.analysis;

import org.koko.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseABindExpr(ABindExpr node);
    void caseAPureExpr(APureExpr node);
    void caseAFundefBindExpr(AFundefBindExpr node);
    void caseACmpPureExpr(ACmpPureExpr node);
    void caseACondPureExpr(ACondPureExpr node);
    void caseANumberPureExpr(ANumberPureExpr node);
    void caseAVarPureExpr(AVarPureExpr node);
    void caseAArgtupFunArg(AArgtupFunArg node);

    void caseTComma(TComma node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTSemicolon(TSemicolon node);
    void caseTCmp(TCmp node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTInt(TInt node);
    void caseTNumber(TNumber node);
    void caseTIdentifier(TIdentifier node);
    void caseTBlank(TBlank node);
    void caseTComment(TComment node);
    void caseEOF(EOF node);
}
