/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import java.util.*;
import expression.analysis.*;

@SuppressWarnings("nls")
public final class ATextualExp extends PExp
{
    private final LinkedList<PTextual> _textual_ = new LinkedList<PTextual>();

    public ATextualExp()
    {
        // Constructor
    }

    public ATextualExp(
        @SuppressWarnings("hiding") List<?> _textual_)
    {
        // Constructor
        setTextual(_textual_);

    }

    @Override
    public Object clone()
    {
        return new ATextualExp(
            cloneList(this._textual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATextualExp(this);
    }

    public LinkedList<PTextual> getTextual()
    {
        return this._textual_;
    }

    public void setTextual(List<?> list)
    {
        for(PTextual e : this._textual_)
        {
            e.parent(null);
        }
        this._textual_.clear();

        for(Object obj_e : list)
        {
            PTextual e = (PTextual) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._textual_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._textual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._textual_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PTextual> i = this._textual_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTextual) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
